//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupuje
    {
        public int MusterijaRedniBroj { get; set; }
        public int SpremaKuvarJMBG { get; set; }
        public int SpremaNudiRestoranIDRestorana { get; set; }
        public string SpremaNudiProizvodNaziv { get; set; }
    
        public virtual Musterija Musterija { get; set; }
        public virtual Sprema Sprema { get; set; }
    }
}
