//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musterija
    {
        public int RedniBroj { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> StoBrojStola { get; set; }
        public Nullable<int> StoRestoranIDRestorana { get; set; }
    
        public virtual Sto Sto { get; set; }
    }
}
