//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprema
    {
        public int KuvarJMBG { get; set; }
        public int NudiRestoranIDRestorana { get; set; }
        public string NudiProizvodNaziv { get; set; }
    
        public virtual Kuvar Kuvar { get; set; }
        public virtual Nudi Nudi { get; set; }
    }
}
