//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sto
    {
        public int BrojStola { get; set; }
        public int BrojMesta { get; set; }
        public string Tip { get; set; }
        public int RestoranIDRestorana { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
